name: Build OGX-Mini RP2040

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive   # importante para Bluepad32 y BTStack

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib ninja-build

      - name: Create Build Folder
        run: mkdir -p Firmware/RP2040/build

      - name: Build OGX-Mini for RP2040
        run: |
          cd Firmware/RP2040
          cmake -S . -B build -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DOGXM_BOARD=PI_PICO \
                -DMAX_GAMEPADS=1
          cmake --build build --config Release

      - name: Upload UF2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ogx-mini-rp2040
          path: Firmware/RP2040/build/OGX-Mini-*-PI_PICO.uf2
