name: Build OGX-Mini

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: [PI_PICO] # Solo dejamos la Pico estándar

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

      - name: Get Pico SDK
        run: git clone --branch 2.1.0 --recurse-submodules https://github.com/raspberrypi/pico-sdk.git

      - name: Create Build and Output Folders
        run: mkdir -p build output

      - name: Build OGX-Mini - ${{ matrix.board }}
        run: |
          cd build
          cmake -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk \
                -DCMAKE_BUILD_TYPE=Release \
                -DOGXM_BOARD=${{ matrix.board }} \
                -DMAX_GAMEPADS=1 \
                ../Firmware/RP2040
          cmake --build .
          
          # Buscar el archivo .uf2 generado y moverlo a la carpeta de salida
          FILE=$(find . -maxdepth 1 -name "OGX-Mini-*-${{ matrix.board }}.uf2" | head -n 1)
          cp "$FILE" ../output/

      - name: Upload UF2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uf2-${{ matrix.board }}
          path: output/*.uf2

  release:
    needs: build
    runs-on: ubuntu-latest
    # Solo crea el release si hay un tag o es un push manual/main
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: all_artifacts
          merge-multiple: true

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          draft: true
          files: all_artifacts/*.uf2
